// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVP-ar2-IWYe4hndKRWxP4w6jhKnQc_8',
    appId: '1:1078504427169:web:23bb670593f0fd079e6ae0',
    messagingSenderId: '1078504427169',
    projectId: 'ergo-delivery',
    authDomain: 'ergo-delivery.firebaseapp.com',
    storageBucket: 'ergo-delivery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpSXtvN58lSDgYQowABIKD9COUsKZnyc',
    appId: '1:1078504427169:android:26aed0d2f67805c09e6ae0',
    messagingSenderId: '1078504427169',
    projectId: 'ergo-delivery',
    storageBucket: 'ergo-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlr4kQ968liUu6XAikaGJGS5ajZO4A7I',
    appId: '1:1078504427169:ios:ce18f42d81b4c53c9e6ae0',
    messagingSenderId: '1078504427169',
    projectId: 'ergo-delivery',
    storageBucket: 'ergo-delivery.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlr4kQ968liUu6XAikaGJGS5ajZO4A7I',
    appId: '1:1078504427169:ios:ce18f42d81b4c53c9e6ae0',
    messagingSenderId: '1078504427169',
    projectId: 'ergo-delivery',
    storageBucket: 'ergo-delivery.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
